#!/bin/bash
function pause(){
   read -p "$*"
}
echo "==============================================================================";
echo "                 KÍNH THƯA CỤ. CON ĐÃ CÀI XONG DIRECT ADMIN:";
echo "       -  BÂY GIỜ MỜI CỤ ĐỔI PASS SAU KHI ENTER ĐỂ CON CÒN BEST CONFIG Ạ  -";
echo "";
echo "==============================================================================";
pause '                      MỜI CỤ [Enter] ĐỂ CON TIẾP TỤC...';
echo "==============================================================================";
echo "";
passwd admin;
wget https://raw.githubusercontent.com/minhvinhdao/final-DA/main/crontab -P /root && chmod 644 /root/crontab;
cd /usr/local/directadmin/conf/;
echo "==============================================================================";
echo "                         check_subdomain_owner=0";
echo "==============================================================================";
pause '                        Nhấn [Enter] để tiếp tục...';
echo "==============================================================================";
echo "";
vi /usr/local/directadmin/conf/directadmin.conf;
vi directadmin.conf;
killall -9 directadmin;
/etc/init.d/directadmin start;
vi /etc/ssh/sshd_config;
service sshd restart;
vi /etc/csf/csf.conf;
cd /usr/local/directadmin/custombuild/;
mkdir -p custom/openlitespeed/conf;
cp -p configure/openlitespeed/conf/httpd-expires.conf custom/openlitespeed/conf/;
rm -rf /usr/local/directadmin/custombuild/custom/openlitespeed/conf/httpd-expires.*;
wget https://raw.githubusercontent.com/minhvinhdao/final-DA/main/httpd-expires.conf -P /usr/local/directadmin/custombuild/custom/openlitespeed/conf/;
chmod 644 /usr/local/directadmin/custombuild/custom/openlitespeed/conf/httpd-expires.conf;
sudo yum install epel-release -y;
yum install redis -y;
rm -f /etc/redis.conf;
wget https://raw.githubusercontent.com/minhvinhdao/final-DA/main/redis.conf -P /etc && chmod 640 /etc/redis.conf;
systemctl stop redis.service;
systemctl disable redis;
cd /root;
wget https://raw.githubusercontent.com/poralix/directadmin-utils/master/php/php-extension.sh -O php-extension.sh && chmod 750 php-extension.sh &&./php-extension.sh install redis;
rm -f /root/php-extension.sh;
systemctl status redis.service;
php -i | grep redis;
yum install memcached -y;
yum install memcached-devel -y;
yum install libmemcached-devel -y;
yum install libmemcached -y;
rm -rf /etc/sysconfig/memcached;
wget https://raw.githubusercontent.com/minhvinhdao/final-DA/main/memcached -P /etc/sysconfig/;
chmod 644 /etc/sysconfig/memcached;
cd /usr/local/directadmin/scripts/custom;
wget https://raw.githubusercontent.com/poralix/directadmin-utils/master/php/php-extension.sh -O php-extension.sh;
chmod 750 php-extension.sh;
./php-extension.sh;
./php-extension.sh install memcached;
./php-extension.sh status memcached;
systemctl restart memcached;
netstat -nltp | grep 11211;
netstat -nltp | grep memcached;
mkdir -p /usr/local/directadmin/custombuild/custom/opcache/;
cp -fp configure/opcache/* /usr/local/directadmin/custombuild/custom/opcache/;
rm -rf /usr/local/directadmin/custombuild/custom/opcache/opcache.ini;
wget https://raw.githubusercontent.com/minhvinhdao/final-DA/main/opcache.ini -P /usr/local/directadmin/custombuild/custom/opcache && chmod 644 /usr/local/directadmin/custombuild/custom/opcache/opcache.ini;
rm -f /usr/local/directadmin/custombuild/configure/opcache/opcache.ini;
wget https://raw.githubusercontent.com/minhvinhdao/final-DA/main/opcache.ini -P /usr/local/directadmin/custombuild/configure/opcache/ && chmod 644 //usr/local/directadmin/custombuild/configure/opcache/opcache.ini;
/usr/local/directadmin/custombuild/build set opcache yes to yes;
/usr/local/directadmin/custombuild/build opcache;
php -i | grep opcache;
/usr/local/directadmin/directadmin set one_click_pma_login 1 && service directadmin restart;
/usr/local/directadmin/custombuild/build update;
/usr/local/directadmin/custombuild/build phpmyadmin;
/usr/local/directadmin/custombuild/build rewrite_confs;
cd /usr/local/directadmin/conf/
rm -f php.ini;
wget https://raw.githubusercontent.com/minhvinhdao/final-DA/main/php.ini;
chmod 644 php.ini;
rm -f /usr/local/php56/lib/php.ini;
rm -f /usr/local/php73/lib/php.ini;
rm -f /usr/local/php74/lib/php.ini;
rm -f /usr/local/php80/lib/php.ini;
wget https://raw.githubusercontent.com/minhvinhdao/final-DA/main/php56/php.ini -P /usr/local/php56/lib && chmod 644 /usr/local/php56/lib/php.ini;
wget https://raw.githubusercontent.com/minhvinhdao/final-DA/main/php73/php.ini -P /usr/local/php73/lib && chmod 644 /usr/local/php73/lib/php.ini;
wget https://raw.githubusercontent.com/minhvinhdao/final-DA/main/php74/php.ini -P /usr/local/php74/lib && chmod 644 /usr/local/php74/lib/php.ini;
wget https://raw.githubusercontent.com/minhvinhdao/final-DA/main/php80/php.ini -P /usr/local/php80/lib && chmod 644 /usr/local/php80/lib/php.ini;
rm -f /etc/localtime;
ln -s /usr/share/zoneinfo/Asia/Ho_Chi_Minh /etc/localtime;
date;
wget https://raw.githubusercontent.com/minhvinhdao/final-DA/main/add-domain.txt -P /var/www/html/ && chmod 644 /var/www/html/add-domain.txt;
history -c;
pause '                        Nhấn [Enter] để tiếp tục...';
reboot